version: "2.1"

services:
  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - TZ=America/New_York
      - ADVERTISE_IP=http://192.168.4.32:32400/
      - PLEX_CLAIM= #optional
    # volumes: 
    #  - /home/ubuntu/media/hdd/Media:/media
    #  - /home/ubuntu/media/hdd/Media/Movies:/movies
    restart: unless-stopped